version: '3.6'
services:
  payara-micro:
    container_name: payara-micro
    image: payara/micro:5.2022.2-jdk11
    ports:
      - 28080:8080
      - 26900:6900
    expose:
      - 8080
      - 6900
    volumes:
      - ../../../../servlet-with-ldap-identity-store/target/servlet-with-ldap-identity-store.war:/opt/payara/deployments/servlet-with-ldap-identity-store.war
      - ../../../../servlet-with-jdbc-identity-store/target/servlet-with-jdbc-identity-store.war:/opt/payara/deployments/servlet-with-jdbc-identity-store.war
      - ../../../../mutiny/target/mutiny.war:/opt/payara/deployments/mutiny.war
  payara-full:
    container_name: payara-full
    image: payara/server-full:5.2022.2-jdk11
    ports:
      - 18080:8080
      - 18081:8081
      - 14848:4848
      - 19009:9009
    expose:
      - 8080
      - 8081
      - 4848
      - 9009
    volumes:
      - ../../../../servlet-with-ldap-identity-store/target/servlet-with-ldap-identity-store.war:/opt/payara/deployments/servlet-with-ldap-identity-store.war
      - ../../../../servlet-with-jdbc-identity-store/target/servlet-with-jdbc-identity-store.war:/opt/payara/deployments/servlet-with-jdbc-identity-store.war
      - ../../../../mutiny/target/mutiny.war:/opt/payara/deployments/mutiny.war
      - ./scripts/init.sql:/opt/payara/init.sql
